# https://docs.netlify.com/configure-builds/file-based-configuration

[build]
publish = "build/webpack/production"

[build.processing]
skip_processing = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
