name: CI
"on":
  - push
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run prettier:check
      - run: pnpm run isort:check

  tsc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run tsc

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test

  webpack:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run webpack

  playwright:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.29.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpx playwright install --with-deps
      - run: pnpm run test:playwright
